# Generated by Django 4.1.7 on 2023-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100)),
                ('Saddress', models.TextField()),
                ('Smail', models.EmailField(max_length=254)),
            ],
        ),
    ]
