# Generated by Django 4.1.7 on 2023-05-17 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naveen', '0002_alter_school_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Sid',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='Sname',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Z]')]),
        ),
    ]
